# nginx proxy address - http://172.17.0.1:62000

name: test
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: test:latest
    container_name: test-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: test-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:62000:3000'
    volumes:
      - './volumes/data:/data:z'
      - './volumes/config:/config:z'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://test-app:3000'
      - 'cloudflare.hostname=test.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.test-app.entrypoints=http'
      - 'traefik.http.routers.test-app-secure.tls=true'
      - 'traefik.http.routers.test-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.test-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.test-app.middlewares=test-app-https-redirect'
      - 'traefik.http.routers.test-app-secure.entrypoints=https'
      - 'traefik.http.routers.test-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.test-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.test-app-secure.service=test-app'
      - 'traefik.http.services.test-app.loadbalancer.server.port=3000'
    networks:
      - test
      - proxy
      - cloudflare

networks:
  test:
    name: test
    external: false
  proxy:
    external: true
  cloudflare:
    external: true

